# Generated by Django 3.0.7 on 2020-06-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
