# Generated by Django 3.0.7 on 2020-06-25 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200625_0207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
    ]
